---
- name: Deploy MERN Application with Nginx
  hosts: all
  become: yes

  vars:
    repo_url: "git@github.com:Kundan547/Mern-Application.git"
    web_server_ip: "3.145.67.122"
    db_server_ip: "10.0.2.183"
    project_dir: "/home/ubuntu/Mern-Application"

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - nginx
          - nodejs
          - npm
          - git
        state: present

    - name: Clone MERN application repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        version: main
        force: yes

    - name: Install frontend dependencies
      command: npm install
      args:
        chdir: "{{ project_dir }}/frontend"

    - name: Build the frontend
      command: npm run build
      args:
        chdir: "{{ project_dir }}/frontend"

    - name: Install backend dependencies
      command: npm install
      args:
        chdir: "{{ project_dir }}/backend"

    - name: Create Nginx configuration for MERN app
      copy:
        dest: /etc/nginx/sites-available/mern_app
        content: |
          server {
              listen 80;
              server_name {{ web_server_ip }};

              root {{ project_dir }}/frontend/build;
              index index.html;

              location / {
                  try_files $uri /index.html;
              }

              location /api/ {
                  proxy_pass http://localhost:3001;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }

              error_page 404 /index.html;
          }
      notify: Restart Nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/mern_app
        dest: /etc/nginx/sites-enabled/mern_app
        state: link

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
