trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x' # Use a recent Node.js version
  displayName: 'Install Node.js'

- script: |
    cd backend
    npm install
    npm run build
  displayName: 'npm install and build'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
  displayName: 'Install Python (for AWS CLI)'

- script: |
    python3 -m pip install --upgrade pip
    pip install awscli
  displayName: 'Install AWS CLI'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'EC2-Instance-Connection' # Set up your service connection
    sourceFolder: 'backend' # Path to your backend directory
    targetFolder: '/home/ec2-user/backend' # Target path on the EC2 instance
  displayName: 'Copy files to EC2 instance'

- script: |
    ssh -o StrictHostKeyChecking=no ec2-user@$(EC2_PUBLIC_IP) <<EOF
    cd /home/ec2-user/backend
    npm install
    pm2 restart index.js || pm2 start index.js
    EOF
  displayName: 'Restart Application on EC2'
