- name: Setup Database Server
  hosts: dbserver
  become: true
  vars_prompt:
    - name: "mongo_password"
      prompt: "Enter the MongoDB password for user 'kundanvyas197'"
      private: yes
  tasks:
    - name: Update the apt cache
      apt:
        update_cache: yes

    - name: Install gnupg and curl
      apt:
        name: 
          - gnupg
          - curl
        state: present

    - name: Import MongoDB public key
      shell: |
        curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | gpg --dearmor -o /usr/share/keyrings/mongodb-server-8.0.gpg
      args:
        executable: /bin/bash
        creates: /usr/share/keyrings/mongodb-server-8.0.gpg

    - name: Add MongoDB repository
      copy:
        content: |
          deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/8.0 multiverse
        dest: /etc/apt/sources.list.d/mongodb-org-8.0.list

    - name: Update the apt cache again after adding MongoDB repo
      apt:
        update_cache: yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present

    - name: Install MongoDB shell
      apt:
        name: mongodb-mongosh
        state: present

    - name: Start MongoDB service
      service:
        name: mongod
        state: started
        enabled: true

    - name: Connect to MongoDB Atlas and verify connection
      shell: |
        echo "{{ mongo_password }}" | mongosh "mongodb+srv://merncluster.pz1lu.mongodb.net/" --apiVersion 1 --username kundanvyas197 --password
      args:
        executable: /bin/bash
      register: mongo_connection
      changed_when: false

    - name: Display MongoDB connection output
      debug:
        var: mongo_connection.stdout
